version: "3.9"
services:
  mydb:
    image: postgres:15.1
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "mydb"
      POSTGRES_PASSWORD: "mydb"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - mydb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  api:
    image: googoogoojoob/model_api:latest
    depends_on:
      - "mydb"
    links:
      - "mydb"
    ports:
      - "8866:8866"
    restart: unless-stopped

volumes:
  mydb:
